
export const READING_PASSAGES: Record<string, { title: string; subtitle: string; content: string[] }> = {
  'r-p1-underground': {
    title: "Answers Underground",
    subtitle: "Burying greenhouse gases to slow global warming",
    content: [
      "A. One way to slow global warming is to take the greenhouse gases that cause it and bury them. That is the idea behind projects now under way to capture emissions from power plants and factories and force them underground or deep into the ocean. There, proponents argue, they could be trapped for thousands of years.",
      "B. This concept, known as carbon sequestration, is already being used by oil companies to improve the efficiency of oil wells, and now engineers have begun exploring ways to capture carbon dioxide emissions from power plants to reduce their impact on the environment. At a recent conference, delegates from fourteen industrialised and developing countries agreed to engage in cooperative research into capturing and storing carbon dioxide.",
      "C. The goal is to stabilise emissions of greenhouse gases that trap heat in the atmosphere. Over the past century, airborne carbon dioxide concentrations have risen by nearly a third, according to Scott Klara, sequestration manager at the US National Energy Technology Laboratory. Unless emissions are slashed by two thirds worldwide, the Intergovernmental Panel on Climate Change predicts that concentrations will rise to double the levels of the early 1700s, before the Industrial Revolution. These increased levels of carbon-based compounds in the atmosphere are believed to be the cause of rising temperatures and sea levels around the world. Ignoring the problem is therefore not an option.",
      "D. Limiting emissions, however, is not an easy undertaking since increased energy consumption is a key to economic growth. Two thirds of the world's power-generating capacity, expected to come into use by 2030, has not been constructed yet, according to the International Energy Agency. The developing world will be particularly important. China and India alone are expected to account for two thirds of the global increase in coal usage over the next fifteen years.",
      "E. Solutions are being sought. Work is being undertaken with alternatives to fossil fuels such as wind and solar energy, but it will be a long time before these alternative sources play a major role in fulfilling the world's energy needs. Geophysicist Klaus Lackner points out that around 85% of the world's energy is derived from fossil fuels, the cheapest and most plentiful energy source available, and the developing world in particular is unlikely to give them up. That is why many scientists support sequestration.",
      "F. However, several problems must be resolved before sequestration plays a key role in a low-carbon future. One is the cost of capturing carbon dioxide. A second is storing the gas safely once it's been captured. Today, it costs about $US50 to extract and store a tonne of carbon dioxide from a power plant, which raises the cost of producing electricity by 30-80%. Lackner argues that it is too expensive to adapt existing plants to capture carbon dioxide. Instead, he recommends that carbon-capturing capacity be built into future plants. Economic incentives are needed to encourage companies to identify low-cost carbon-sequestration solutions. A government-supported program in the US has enabled some factories to partially capture carbon emissions, which they then sell for various uses, including carbonating soft drinks. However, there are no power plants ready for full carbon capture.",
      "G. Once the carbon has been captured it must be stored. Natural carbon sinks*, such as forests and wetlands, can remove some carbon dioxide from the atmosphere, but not nearly enough. Carbon dioxide could be pumped to the bottom of the ocean, where the pressure would keep it pinned to the seabed in liquid form for decades, but that has serious long-term environmental risks. David Hawkins, from the Natural Resources Defense Council in Washington, warns that the carbon dioxide could radically alter the chemical balance in the ocean, with potentially harmful consequences for marine life. Others worry that the carbon dioxide could escape back into the atmosphere.",
      "H. A few promising attempts at underground carbon sequestration are currently under way. In western Canada, an oil company is pumping liquefied carbon dioxide into oil wells to force more oil to the surface and boost recovery by 10-15%. The company gets the carbon dioxide via a pipeline from North Dakota in the US, where the gas is captured from a synthetic-fuel plant. In another instance in the North Sea, a Norwegian energy firm is injecting carbon dioxide waste from its natural-gas operations into a saline aquifer 1,000 metres beneath the ocean floor.",
      "I. Clearly, storing large amounts of gas underground raises environmental fears. Environmentalists argue that more research is needed on potential storage sites, such as oil and gas reservoirs and coal seams unsuitable for mining, to ensure that they offer long-term solutions. The World Wide Fund for Nature Australia has argued that the primary risk of underground storage is that dangerously large volumes of carbon dioxide might escape and people become asphyxiated.",
      "J. Little progress in slashing global greenhouse gases can be achieved without involving developing countries, but for now carbon sequestration is not their priority because of the increased costs this would add to energy production. Hawkins argues that, to encourage developing nations to use sequestration, developed nations will have to provide assistance. He suggests a multilateral initiative in which developed nations, perhaps by purchasing carbon credits from poorer countries, finance the difference between the cost of a regular coal-fired power plant and one that captures carbon emissions. That is, the rich – who will remain the world's biggest polluters for years to come – would buy the right to emit carbon from the poor, who would use the proceeds to build better plants.",
      "* carbon sinks: natural features of the environment which absorb carbon dioxide"
    ]
  },
  'r-p1': {
    title: "Ambergris",
    subtitle: "What is it and where does it come from?",
    content: [
      "Ambergris was used to perfume cosmetics in the days of ancient Mesopotamia and almost every civilization on the earth has a brush with Ambergris. Before 1,000 AD, the Chinese named ambergris as 'lung sien hiang,' 'dragon's spittle perfume,' as they thought that it was produced from the drooling of dragons sleeping on rocks at the edge of a sea. The Arabs knew ambergris as 'anbar' who believed that it is produced from springs near seas. It also gets its name from here. For centuries, this substance has also been used as a flavouring for food.",
      "During the Middle Ages, Europeans used ambergris as a remedy for headaches, colds, epilepsy, and other ailments. In the 1851 whaling novel Moby-Dick, Herman Melville claimed that ambergris was 'largely used in perfumery.' But nobody ever knew where it really came from. Experts were still guessing its origin thousands of years later, until the long ages of guesswork ended in the 1720's, when Nantucket whalers found gobs of the costly material inside the stomachs of sperm whales.",
      "Industrial whaling quickly burgeoned. By 20th century ambergris is mainly recovered from inside the carcasses of sperm whales.",
      "Through countless ages, people have found pieces of ambergris on sandy beaches. It was named grey amber to distinguish it from golden amber, another rare treasure. Both of them were among the most sought-after substances in the world, almost as valuable as gold. (Ambergris sells for roughly $20 a gram, slightly less than gold at $30 a gram.) Amber floats in salt water, and in old times the origin of both these substances was mysterious. But it turned out that amber and ambergris have little in common. Amber is a fossilized resin from trees that was quite familiar to Europeans long before the discovery of the New World, and prized for jewelry. Although considered a gem, amber is a hard, transparent, wholly-organic material derived from the resin of extinct species of trees, mainly pines.",
      "To the earliest Western chroniclers, ambergris was variously thought to come from the same bituminous leaf fountains as amber, from the sperm of fishes or whales, from the droppings of strange sea birds (probably because of confusion over the included beaks of squid) or from the large hives of bees living near thesea. Marco Polo was the first Western chronicler who correctly attributed ambergris to sperm whales and its vomit.",
      "As sperm whales navigate in the oceans, they often dive down to 2km or more below sea level to prey on squid, most famously the Giant Squid. It's commonly accepted that ambergris forms in the whale's gut or intestines as the creature attempts to 'deal' with squid beaks. Sperm whales are rather partial to squid, but seemingly struggle to digest the hard, sharp, parrot-like beaks. It is thought their stomach juices become hyper-active trying to process the irritants, and eventually hard, resinous lumps are formed around the beaks, and then expelled from their innards by vomiting.",
      "When a whale initially vomits up ambergris, it is soft and has a terrible smell. Some marine biologists compare it to the unpleasant smell of cow dung. But after floating on the salty ocean for about a decade, the substance hardens with air and sun into a smooth, waxy, usually rounded piece of nostril heaven. The dung smell is gone, replaced by a sweet, smooth, musky and pleasant earthy aroma.",
      "Since ambergris is derived from animals, naturally a question of ethics arises, and in the case of ambergris, it is very important to consider. Sperm whales are an endangered species, whose populations started to decline as far back as the 19th century due to the high demand for their highly emollient oil, and today their stocks still have not recovered. During the 1970's, the Save the Whales movement brought the plight of whales to international recognition. Many people now believe that whales are 'saved'. This couldn't be further from the truth. All around the world, whaling still exists. Many countries continue to hunt whales, in spite of international treaties to protect them.",
      "One of the forms ambergris is used today is as a valuable fixative in perfumes to enhance and prolong the scent. But nowadays, since ambergris is rare and expensive, and big fragrance suppliers that make most of the fragrances on the market today do not deal in it for reasons of cost, availability and murky legal issues, most perfumeries prefer to add a chemical derivative which mimics the properties of ambergris."
    ]
  },
  'r-cultural-tourist': {
    title: "An early cultural tourist",
    subtitle: "Cyriacus of Ancona's travels in the 15th century",
    content: [
      "A. In the fifteenth century, a young Italian merchant named Cyriacus of Ancona began traveling around the Mediterranean, visiting the ruins of ancient Greece and Rome. He was not just a trader, but also a pioneer of cultural tourism. His travels were driven by a desire to learn about the ancient world and to document its wonders.",
      "B. Cyriacus was born in Ancona, a port city on the Adriatic coast of Italy. He came from a family of merchants and learned the trade from a young age. As a young man, he traveled extensively throughout the Mediterranean, visiting ports and markets in Greece, Turkey, and Egypt.",
      "C. During his travels, Cyriacus became fascinated by the ancient ruins he encountered. He began to study the history and architecture of the places he visited, and he started to make detailed notes and drawings. He was particularly interested in Greek and Roman temples, theaters, and public buildings.",
      "D. Cyriacus was not the first person to visit the ancient ruins, but he was one of the first to systematically study and document them. He kept detailed journals of his travels, including descriptions of the ruins, sketches of the monuments, and copies of inscriptions he found.",
      "E. His travels were not without danger. In the fifteenth century, the Mediterranean was a dangerous place, with pirates, bandits, and political instability. Cyriacus faced many challenges during his journeys, but his passion for learning kept him going.",
      "F. One of Cyriacus's most famous journeys was to Greece, where he visited Athens, Delphi, and other ancient sites. He was particularly interested in the Parthenon in Athens, which he described as one of the most magnificent buildings he had ever seen.",
      "G. Cyriacus's work was ahead of its time. He understood the importance of preserving the ancient world's heritage and of sharing knowledge with others. He corresponded with scholars across Europe and sent them copies of his drawings and notes.",
      "H. Today, Cyriacus of Ancona is remembered as one of the pioneers of archaeology and cultural tourism. His travels and documentation helped to inspire a renewed interest in the ancient world during the Renaissance.",
      "I. His work also highlights the importance of cultural exchange and understanding. By traveling to different countries and learning about their histories, Cyriacus helped to bridge the gap between different cultures.",
      "J. Cyriacus's legacy continues to inspire travelers and scholars today. His example shows that travel can be a powerful tool for learning and personal growth."
    ]
  },
  'r-ascension': {
    title: "The Ascension Island experiment",
    subtitle: "How Darwin transformed a barren volcanic rock into a forest",
    content: [
      "The tiny tropical island of Ascension in the South Atlantic Ocean has an area of only 98 square kilometres. It is located 1,600 km from the coast of Africa and 2,250 km from South America and is certainly difficult for an ordinary commercial traveler to reach even today. Ascension sits on top of what scientists call the mid-Atlantic ridge. This is a chain of underwater volcanoes which are still in the process of forming as the ocean floor is slowly pulled apart by massive geological forces. A million years ago, molten magma from beneath the ocean floor burst explosively above the waves and thus, a new island was born which was to become Ascension. Because the island occupies a 'hot spot' on the ridge, its volcano is especially active to this day.",
      "The island was discovered by a Portuguese seafarer, João da Nova Castella, in 1501, but was given the name Ascension Island two years later by a second Portuguese explorer, Alfonso de Albuquerque. At that time, Ascension was little more than a barren volcanic rock, largely treeless, with no indigenous people at all and no animals to speak of. Its coastal regions, however, supported a few small, underdeveloped plants, while the central peaks were essentially bald.",
      "Because of its location, by the early 19th century, Ascension had become a vital strategic base for the British military. It was a thriving waystation providing much needed provisions for British ships. However, the big problem that impeded further expansion of this outpost was the supply of fresh water. Ascension was extremely arid and experienced strong trade winds from southern Africa. Due to the lack of trees, the little rain that did fall swiftly disappeared in the hot environment.",
      "But Charles Darwin, the British naturalist who is widely regarded as the father of the theory of evolution, devised a bold plan for the barren island. In 1836, the young Darwin was finishing a five-year scientific expedition around the world, reaching strange places like Ascension, where no other naturalist had gone before. Darwin was aboard the British Naval vessel HMS Beagle when it called in at Ascension. Darwin later admitted that his expectations of Ascension were low, and indeed, it cannot have appeared to be a very promising place.",
      "But arriving on Ascension, Darwin became excited by what he considered to be its potential. Everywhere, he encountered bright red volcanic cones and rugged black lava, evidence of the violent geological forces that must have formed the island. Although it remained quite barren, there was evidence of human presence, including a few sheep, goats, cows and horses that had been introduced by the Navy. Being the inventive scientist that he was, Darwin was intrigued by what he saw and began to plan how this place of wild desolation could be transformed.",
      "Only a few years after Darwin's return to England, he laid out his imaginative scheme for Ascension to his good friend, Joseph Hooker, also a respected botanist, who ultimately implemented the plan. In 1839 Hooker set off on his own four-year adventure by sea, an ambitious journey around the icy polar region of Antarctica aboard HMS Erebus and HMS Terror. Mirroring Darwin's journey, the ships called in at Ascension on their way home in 1843.",
      "In 1847 Hooker advised the Royal Navy to set in motion Darwin's elaborate plan. With the help of British scientists, shipments of trees were to be sent to Ascension. These would provide shade, helping to reduce evaporation after rain. And the ultimate results of the introduction of trees would be even more important because the retention of water would create fertile soil, encouraging the growth of even more vegetation of all kinds.",
      "So, beginning in 1850 and continuing year after year, ships started to arrive at Ascension, each depositing tree selected from special gardens maintained by scientists in Europe, South Africa and South America. Soon, on the highest peak of 859m, great changes became apparent. By the late 1870s, a variety of trees including fast-growing eucalyptus, Norfolk Island pine, bamboo and banana trees had all taken root and begun to thrive.",
      "Today, Green Mountain — as the highest peak is now known — is sometimes described as a 'cloud forest'. The trees capture sea mist, creating dampness in the centre of an essentially dry island. This forest is a fully functioning, but in fact totally artificial ecosystem. When naturally occurring, ecosystems develop over millions of years through the process of evolution. By contrast, the Green Mountain cloud forest was created in a matter of decades. In effect, what Darwin, Hooker and the Navy achieved in an effort to make Ascension Island more habitable was the world's first experiment in creating a self-sustaining and self-reproducing forest.",
      "Could the Ascension experiment have more far-reaching consequences? Dr Dave Wilkinson, an ecologist at Liverpool John Moores University in the UK, who has extensively studied Ascension and its history, first visited there in 2003. 'I remember thinking, this is really weird,' he said. 'There were all kinds of plants that don't belong together in nature, growing side by side. I only later found out about Darwin, Hooker and everything that had happened,' he later recalled. Wilkinson has suggested that the principles upon which the Ascension experiment was based could one day be used to transform the planet Mars to make it sustainable for colonies from Earth."
    ]
  },
  'r-beatrix-potter': {
    title: "The life of Beatrix Potter",
    subtitle: "The children's author and illustrator who created Peter Rabbit",
    content: [
      "Beatrix Potter is one of the best-selling children's authors of all time. Her popular series of books that includes The Tale of Peter Rabbit was first published over one hundred years ago, and has never been out of print. Generations of children have enjoyed her many stories and illustrations, all of which celebrate the English lifestyle and rural landscape through the adventures of animals.",
      "Born to a comfortable middle-class family in London in 1866, Potter spent much of her early life in her own company. She was educated in her parents' house by a governess and rarely saw her brother Bertram, who was sent to boarding school. Having little social contact with children of her own age, Potter began to be drawn into her own world of writing. When Beatrix was 15, she began to keep a diary written in a secret code of her own invention. Even Beatrix herself, when she read back over it in later life, found it difficult to understand. It was not until 15 years after her death that the code was cracked. To the outside world Beatrix appeared a shy and reserved person, but in her diary she was able to express herself openly, and she was critical of the paintings of a number of artists of the day.",
      "Potter was a naturally gifted artist, and with the aid of some art lessons she also learnt the technical side of drawing. During her childhood, she looked after many animals, such as rabbits, frogs, and even bats. She drew these animals throughout her childhood, gradually improving the standard of her work by sketching in museums. She was also interested in natural history. She would spend many hours drawing wildlife such as fungi and flowers, and at one time she had an ambition to develop this scientific interest. An uncle tried to help her become a student at the Royal Botanic Gardens at Kew in London, but she was rejected because of her gender. Nevertheless, she achieved a measure of respect from the scientific establishment for her illustrations and contribution to mycology, the study of fungi.",
      "When Potter was in her early 20s, her parents tried to arrange a partner for her to marry. Many likely suitors were found; however, Potter turned them all down. She was a fiercely independent woman, and she disliked the idea of being tied down to a domestic life that, at that time, consisted mostly of staying at home and bringing up children. Thus, unusually for British women of those times, she remained single and lived in her parents' home.",
      "For several years, Potter tried to get her first children's book, The Tale of Peter Rabbit, published. Her initial attempts proved unsuccessful, but she persevered and eventually the book was accepted for publication by Frederick Warne & Company. The book finally came out in 1902, when Potter was 36, but the publishers did not expect it would sell many copies. In fact, the project was given to the youngest brother in the family company, Norman Warne, for his first project as a kind of test. Luckily, he proved to be a good choice as he warmed to both the book and Potter. He was determined to make a success of the book and developed a good working relationship with Potter as they pored over the individual details of the book. It was Norman who insisted that each drawing would be in colour. Potter insisted that the book remain small so that it would be easy for children to hold, and by the end of the year, 28,000 copies were in print.",
      "The relationship between Warne and Potter blossomed, and eventually they became engaged. However, Potter's parents were unhappy about this because of his occupation. They eventually relented, but insisted the couple live apart for six months to give Potter time to change her mind. Tragically, before the wedding could take place, Warne developed pernicious anaemia, a blood disease, and passed away. Potter was devastated and she wrote in a letter to his sister, Millie, 'He did not live long, but he fulfilled a useful, happy life. I must try to make a fresh beginning next year.'",
      "After Warne's death, Potter moved to the Lake District in northern England. In 1905 she bought a small farm there, and for the next eight years she busied herself writing more books, some of which were based in or around the area. She lived there for the remainder of her life, but due to failing eyesight she was forced to stop writing children's books. Instead, she devoted her time to the breeding of sheep and helping with the conservation of farms in the district. Using proceeds from her very successful books and later her inheritance, Potter was able to buy many working farms. On her death, she left over 4,000 acres to the National Trust, an organisation which protects historical buildings and areas of countryside in England. It has meant that her beloved countryside is now accessible to many visitors."
    ]
  },
  'r-bondi': {
    title: "Bondi",
    subtitle: "Australia's most famous beach, but how did this come about?",
    content: [
      "Australians have not always valued Sydney's Bondi Beach. Beaches attracted little attention in the first century of British colonial settlement, when it was the country's desert interior that stirred the settlers' imagination. The visual image of Australia was based on stories of explorers searching in the dry red centre for an inland sea, of men driving cattle vast distances, or shearing sheep in hot dusty sheds. It was a cultural landscape developed in hardship and tragedy.",
      "Before the British settlement, there had been a strong traditional connection to the coast among Aboriginal people, the indigenous inhabitants of Australia, and evidence of this connection can still be seen. In 1788 Governor Phillip, who established the first British settlement on the eastern coast of Australia, estimated that there were approximately 1500 Aboriginal people living within a 10-mile radius of Sydney Harbour. But by the 1820s the local Aboriginal population had largely disappeared as a result of contact with the diseases brought by the settlers.",
      "In the minds of the new settlers, Aboriginal culture would come to be predominantly associated with the inland desert. The cultural associations that formed around Australia's beach landscape would, in turn, be almost entirely European in nature. Compared with the 'ancient' and bicultural mythology of Australia's interior, its beach culture would be depicted as being wholly modern and Western.",
      "At the end of the 19th century, the beach emerged in art and literature as an alternative cultural landscape to the mythology of the interior. The two settings were similar in that they shared an idea of purity because of their association with nature, but otherwise they represented vastly different qualities. The interior of the country represented hard work and suffering, while the coast evoked images of health, purity and egalitarianism.",
      "In Britain, the association of beaches with health received royal blessing in 1783 when a prominent member of the royal family attended the health spas at Brighton Beach on the English coast, and built a pavilion there. With its entertainment, hotels and weekend villas, Brighton became the model for beaches throughout Britain's colonies. Reflecting the English resort's influence, seven Sydney beach suburbs still have a Brighton Street.",
      "Sydney's beach suburbs, rising to prominence in the late 19th century, shared Brighton's association with health. The perception of the city's beaches as places of purity and well-being was strengthened by contrast with the increasingly polluted city centre.",
      "By the end of the 19th century, Sydney's beaches had begun to differ in their socio-economic characteristics. The beach in the suburb of Coogee was the first ocean beach to become accessible by tram from the city. Promoted as a garden suburb, Coogee became a recreational meeting place for the city's middle class.",
      "The suburb of Manly, with its beach and esplanade, copied the British resort model, and attracted the city's wealthy class living in the northern suburbs as well as holiday-makers from farms in the countryside.",
      "The suburb of Bondi was developed after Coogee and Manly and took on a character distinct from the city's other beach suburbs. With the extension of the tramline to Bondi in the 1890s, a number of substantial properties were built there. Property developers, expecting continued middle-class development, subdivided the area into house-sized plots. However, a sudden demand for housing in the first decade of the 20th century saw the plans for houses put aside, and investors built blocks of flats instead.",
      "A treeless plain of red-roofed apartments began to spread its way across Bondi. Built with cheap local bricks, the size and quality of the apartments were generally more modest than those in neighbouring suburbs, and quickly attracted a population of rent-paying, working-class tenants.",
      "With tram access extended all the way to the beach, Bondi also became the most accessible ocean beach to people living in the inner city, who were mostly working class. The pleasures of the sun, sea and surf were not only for the wealthy, but free to all. The Australian notion of beaches as places of social equality became established, and Bondi exemplified this precisely.",
      "Bondi's identity as a largely working-class suburb began to change in the 1950s. The suburb and its beach first came to international attention in 1954 when Queen Elizabeth of England and her husband Prince Philip attended a surf carnival there. Since then, Bondi has become one of Sydney's most used sites for large-scale public events.",
      "The film industry quickly built on the fame that Bondi beach acquired as a result of the surf carniv草l, and since then it has been the location of many Australian films. With the expanding use of Bondi as a media setting, the suburb became home to a community of artists as well as film and television workers. Since the 1970s Bondi has become the almost inevitable backdrop for any artistic or commercial project in Sydney that requires a beach setting. Bondi is now famous simply for being famous.",
      "In the preparations for the 2000 Olympic Games, Bondi was nominated to host the 10,000-seat beach volleyball stadium. Some people in the Bondi community did not support the proposal because of concerns for the environment, but the opposition was dismissed by the Olympics Organising Committee. There were good practical reasons for the Committee to support Bondi's hosting of the event, but the main reason the Committee insisted the stadium be built there was the international expectation that Bondi, as Australia's best known beach, would be the stadium's scenic backdrop."
    ]
  },
  'r-prosopagnosia': {
    title: "Prosopagnosia",
    subtitle: "Sorry - who are you?",
    content: [
      "Prosopagnosia is a medical condition that stops people from recognizing people's faces. But how common is it and why does it happen?",
      "It was Jacob Hodes' first day at college. He recalls spending an enjoyable afternoon being shown around campus by a second year student named Daniel Byrne, who happened to be from his home town. Jacob then spent the rest of the year ignoring him. 'I never saw him again,' he says. 'Well, I'm sure I walked past him plenty of times, but I just didn't see him.' This behavior wasn't intentional. Jacob just couldn't recollect what his fellow student looked like. He had had the same trouble all his life. Friends and relatives would greet him and he would have no idea who they were.",
      "It wasn't until five years ago that it all made sense. That was when Hodes was diagnosed with prosopagnosia, a condition that means he is unable to recognise faces. According to researchers, he is far from alone. In fact the condition is not that uncommon but until a few years ago only a few dozen cases had ever been described, and all of these had been caused by brain injury. Recently, though, researchers identified a second form of face blindness: developmental prosopagnosia, which is either present from birth or develops very early in life.",
      "In May a team from Harvard University in the US and University College London (UCL) announced the results of a web survey of 1,600 people, suggesting that up to 2 per cent of people have some degree of face blindness. Then in August, Martina Gruter and colleagues at the Institute for Human Genetics in Munster, Germany, similarly reported that 2.5 per cent of 700 secondary school pupils they had tested had trouble recognising faces. The results of the survey took everyone by surprise.",
      "It seems that if you have never known what it is to recognise a face, you don't necessarily know that you are supposed to be able to. Prosopagnosics almost always know that they have trouble recognising people, but they often don't realise that other people have better recognition skills than they do, says Brad Duchaine, a researcher at UCL.",
      "Despite these issues, the majority of developmental prosopagnosics possess strategies that allow them to get around their difficulty, for instance, by recognising hair, clothing or a person's way of speaking. So, unless they see a familiar person out of context, with a new hairstyle or in different clothes, they can recognise people just fine. Even so, the discovery of developmental prosopagnosia has attracted attention from neuroscientists keen to discover what is different about the brain of face-blind people. This difference, they believe, could help solve the problem of how the brain deals with information in general: not just visual data. In other words, it may show whether the brain has specialised parts for specific tasks or is more of a general-purpose information processor.",
      "One issue, however, that will present challenges for researchers is that no two prosopagnosics are the same. Some have problems only with faces, while others have trouble with ordinary everyday objects and, so it turns out, animals which would normally be familiar as well. Some prosopagnosics can train themselves to recognise specific faces; others can't even recognise their own in a mirror. When some have been tested they could identify the emotion which was conveyed on another's face, even though the face itself seemed unfamiliar, while for other subjects this was an impossibility. Some cannot recognise the faces of old friends or fellow students but have no trouble telling whether a particular face from such groups would be attractive to most people. Because of this diversity, working out the cause of prosopagnosia will not be easy.",
      "In Martina Gruter's study, the prosopagnosics who agreed to have their parents and relatives tested reported at least one with the condition. Having looked at 38 cases in seven families, the German team believe they have good evidence that a single gene could be responsible. Duchaine also has some evidence that face blindness could be inherited but thinks other factors might be more significant. He refers to studies of babies born with a condition which means the eye's lens is not clear, and when it's the left one, being unable to see through this eye during the first two months of life is a major risk factor for prosopagnosia.",
      "Whatever the cause, what most prosopagnosics want to know is whether they can do anything to improve their face recognition skills. Joseph Degutis, a graduate student at the University of California, recently reported successfully training a severe developmental prosopagnosic to recognise faces during tests carried out in the laboratory. The subject also reported that recognising faces in everyday life became easier due to the training. Duchaine now plans to attempt to train sufferers to recognise the five people that they most need to know, maybe their immediate family, for example, and essential colleagues. Thomas Gruter, Martina Gruter's husband, who also works on her team, however, is not convinced it will work. 'I don't know how you can have more training than you have already had,' he says. 'Humans already spend all day looking at faces.' He also points out that cheating is a possibility during tests and provides an example. 'One person we studied said that when she was doing the face-recognition test, she memorised the distance between nose and upper lip. She wasn't the only one.' So you can perform well in the test and not do so well in real life."
    ]
  },
  'r-triumph-city': {
    title: "Triumph of the City",
    subtitle: "Book review: How urban centres drive economic prosperity",
    content: [
      "In his provocative new book 'Triumph of the City', Harvard economist Edward Glaeser challenges the conventional wisdom that cities are crowded, polluted, and unhealthy places that we should flee at the first opportunity. Instead, he argues that cities are humanity's greatest invention and the engine of human progress.",
      "Glaeser begins by tracing the history of urbanisation, showing how cities have always been centres of innovation, trade, and cultural exchange. From ancient Athens and Rome to modern Manhattan and London, cities have attracted ambitious individuals seeking opportunity and connection. The concentration of talented people in close proximity creates what Glaeser calls 'human capital spillovers' - the idea that proximity to smart people makes us smarter.",
      "One of the book's most compelling sections deals with the economic advantages of density. Glaeser presents data showing that denser cities tend to be richer cities. In the United States, New York City, Los Angeles, and San Francisco - among the most densely populated metropolitan areas - also have the highest incomes per capita. This is not a coincidence, argues Glaeser. The ability to easily share ideas, goods, and services in dense environments creates economic opportunities that simply cannot exist in rural or suburban settings.",
      "The author also challenges the environmental argument against cities. While it may seem counterintuitive, Glaeser shows that cities are actually more environmentally friendly than suburban or rural living. Because city residents live in smaller spaces, use cars less frequently, and share infrastructure more efficiently, they have a smaller carbon footprint per capita than their suburban counterparts. The environmental movement's focus on preserving rural landscapes, he argues, may be misplaced.",
      "Glaeser is at his most controversial when he critiques urban planning policies that restrict housing supply and drive up prices. He argues that regulations like zoning laws and building height restrictions prevent cities from growing to meet demand, making housing unaffordable for many. The solution, he suggests, is to allow cities to build up rather than spread out.",
      "The book is not without its critics. Some have pointed out that Glaeser's analysis largely ignores the problems of urban poverty and inequality. While cities may create wealth on average, this wealth is often concentrated among the educated elite, leaving behind those without college degrees. The gleaming towers of the financial district, critics argue, exist in stark contrast to neighborhoods plagued by crime and unemployment.",
      "Despite these criticisms, 'Triumph of the City' remains an important contribution to the debate about urbanisation. Glaeser's data-driven approach provides a compelling case for the continued importance of cities in the 21st century. As the world becomes increasingly urbanised - with more than half the global population now living in cities - understanding how cities work has never been more crucial.",
      "The book's optimism about cities is refreshing in an age of climate anxiety and suburban sprawl. Glaeser reminds us that cities are not problems to be solved but solutions to be celebrated. By bringing people together, cities enable the innovation and collaboration that drive human progress. In this sense, the triumph of the city is really the triumph of human connection.",
      "For policymakers, Glaeser's message is clear: instead of trying to limit urban growth, we should be finding ways to make cities more livable and accessible. This means investing in public transportation, reducing restrictive zoning laws, and ensuring that the benefits of city living are shared by all residents, not just the wealthy."
    ]
  },
  'r-p3': {
    title: "The Megafires of California",
    subtitle: "Understanding the increasing threat of massive wildfires",
    content: [
      "A. In recent years, California has experienced increasingly devastating wildfires. These megafires, defined as fires burning more than 100,000 acres, have become more frequent and destructive. Scientists attribute this trend to a combination of factors including climate change, drought conditions, and decades of fire suppression policies that have led to excessive fuel accumulation in forests.",
      "B. The 2018 Camp Fire was the deadliest and most destructive wildfire in California's history. It destroyed the town of Paradise, killing 85 people and incinerating nearly 14,000 homes. The fire spread at an alarming rate, driven by strong winds and dry conditions. Emergency responders struggled to evacuate residents as roads became impassable and communications systems failed.",
      "C. Climate change has significantly altered California's fire season. Rising temperatures have extended the period of drought conditions, creating ideal conditions for wildfires to ignite and spread. Snowpack in the Sierra Nevada mountains has decreased, reducing water availability and drying out vegetation. These changes have created a landscape primed for catastrophic fires.",
      "D. Forest management practices are also contributing to the problem. For much of the 20th century, the policy of complete fire suppression was implemented, preventing natural fires from clearing out dead trees and undergrowth. This has resulted in dense forests with excessive fuel loads. When fires do start, they burn with unprecedented intensity, making them difficult to control.",
      "E. Urban expansion into wildland areas has increased the risk to human lives and property. The wildland-urban interface, where homes are built adjacent to forests, has expanded dramatically. This puts more people in harm's way and makes firefighting more complex, as crews must prioritize protecting structures while also battling the flames.",
      "F. Firefighting technology has advanced significantly in recent years. Aircraft equipped with infrared sensors can detect hot spots from above, allowing crews to target their efforts more effectively. Drones provide real-time imagery of fire behavior, helping incident commanders make critical decisions. However, these tools are often overwhelmed by the scale and speed of megafires.",
      "G. Community preparedness has become a crucial focus for fire officials. Programs like Firewise encourage homeowners to create defensible space around their properties by clearing vegetation and using fire-resistant building materials. Evacuation planning and public warning systems have also been improved, though challenges remain in reaching all residents in time.",
      "H. The long-term solution requires a comprehensive approach that addresses both climate change and forest management. Prescribed burns, where controlled fires are set to reduce fuel loads, have proven effective but face opposition due to air quality concerns and safety risks. Mechanical thinning of forests, where trees are cut and removed, offers another tool but is expensive and labor-intensive.",
      "I. Insurance companies have responded to the increasing fire risk by raising premiums or withdrawing coverage in high-risk areas. This has created economic pressure on homeowners and raised questions about who should bear the cost of living in fire-prone regions. Some experts argue that stricter building codes and land-use regulations are necessary to reduce future losses.",
      "J. As California continues to grapple with the megafire threat, researchers are working to improve predictive models that can identify high-risk conditions days before a fire starts. By better understanding the interplay between weather, vegetation, and human activity, authorities hope to get ahead of these catastrophic events and protect both lives and communities."
    ]
  },
  // PASSAGE 2
  'r-p2-computer-games': {
    title: "Computer Games",
    subtitle: "The impact of gaming on learning and development",
    content: [
      "Computer games have become one of the most popular forms of entertainment in the modern world. From simple puzzle games to complex role-playing adventures, millions of people spend countless hours immersed in virtual worlds. But what impact do these games have on our minds and behaviour?",
      "Research into the effects of computer games has produced mixed results. Some studies suggest that certain types of games can improve visual-spatial skills, hand-eye coordination, and problem-solving abilities. Action games, in particular, have been linked to enhanced attention and faster reaction times. These findings have led some educators to explore the potential of games as learning tools.",
      "The concept of 'edutainment' - educational entertainment - has gained popularity in recent years. Developers have created games specifically designed to teach subjects like mathematics, history, and foreign languages. Proponents argue that these games can make learning more engaging and effective by tapping into the motivational power of gameplay.",
      "However, critics raise concerns about the potential negative effects of excessive gaming. Studies have linked heavy game playing to attention problems, obesity, and decreased academic performance. The immersive nature of many modern games, with their elaborate storylines and reward systems, can make it difficult for players to disengage and return to real-world responsibilities.",
      "Violent video games have been a particular source of controversy. Some researchers have found correlations between exposure to violent game content and aggressive behaviour, desensitisation to violence, and reduced prosocial behaviour. However, other researchers have questioned the methodology and conclusions of these studies, pointing out that establishing causality is difficult in this field.",
      "The gaming industry has responded to these concerns by introducing features designed to promote healthy gaming habits. Many games now include systems that remind players to take breaks, and parental control tools allow parents to limit their children's play time. Some countries have also implemented rating systems to help consumers make informed decisions about game content.",
      "As technology continues to advance, the potential for games to impact our lives will only increase. Virtual reality and augmented reality technologies are already being explored for applications beyond entertainment, including therapy, training, and education. The key challenge will be harnessing the power of these technologies while mitigating their potential harms.",
      "For now, the debate about the effects of computer games is likely to continue. While some people see games as a waste of time or even a danger to society, others view them as a powerful medium with the potential to educate, inspire, and connect people around the world."
    ]
  },
  'r-p2-chocolate': {
    title: "Chocolate for the Masses",
    subtitle: "How chocolate became a global commodity",
    content: [
      "Chocolate has a long and fascinating history that stretches back thousands of years. The cacao plant, from which chocolate is derived, was first cultivated by ancient Mesoamerican civilizations such as the Olmec, Maya, and Aztec. These cultures valued cacao beans so highly that they were used as currency and played a central role in religious ceremonies.",
      "When the Spanish conquistadors arrived in the Americas in the 16th century, they encountered chocolate and eventually brought it back to Europe. Initially, chocolate was consumed primarily as a bitter drink, often mixed with spices. It was the European addition of sugar, and later milk, that transformed chocolate into the sweet treat we know today.",
      "The industrial revolution brought significant changes to chocolate production. In the 19th century, inventors developed machines that could process cacao beans on a large scale, making chocolate more affordable and accessible to the general population. The invention of milk chocolate by Daniel Peter in Switzerland, and the development of the cocoa press by Conrad Van Houten, were particularly important innovations.",
      "The 20th century saw chocolate become a truly global industry. Major companies established supply chains that spanned continents, sourcing cacao from West Africa, Southeast America, and other tropical regions. Today, the global chocolate industry is worth billions of dollars and employs millions of people, from farmers who grow cacao to workers in factories and shops.",
      "However, the chocolate industry faces significant challenges. The demand for cacao has led to deforestation in many producing regions, as forests are cleared to make way for cacao farms. There are also concerns about labour practices on cacao farms, with reports of child labour and poor working conditions in some areas.",
      "In response to these challenges, many chocolate companies have adopted sustainable sourcing practices. Fair trade certification, which guarantees that farmers receive a minimum price for their cacao, has become increasingly common. Some companies have also invested in programs to improve farming practices and support local communities.",
      "Consumer preferences have also evolved in recent years. There is growing demand for organic and specialty chocolates, as well as for dark chocolate with higher cacao content. Health-conscious consumers are driving innovation in the industry, with new products that promise lower sugar content or added health benefits.",
      "Despite these changes, chocolate remains one of the world's most beloved treats. Whether enjoyed as a simple candy bar or as part of an elaborate dessert, chocolate continues to bring pleasure to people of all ages around the globe."
    ]
  },
  // PASSAGE 3
  'r-p3-feeding-world': {
    title: "Feeding the World",
    subtitle: "The challenges of global food security",
    content: [
      "The global population is projected to reach 9.7 billion by 2050, presenting an enormous challenge for food production. Already, nearly 800 million people suffer from chronic hunger, while millions more lack access to nutritious food. How will we feed a growing world population without destroying the planet in the process?",
      "One approach is to increase agricultural productivity through technology and innovation. Genetically modified organisms, precision farming, and advanced irrigation systems have all been promoted as ways to produce more food on existing farmland. Proponents argue that these technologies are essential to meet future food demand without converting more natural habitats to agricultural use.",
      "However, critics point out that technological solutions alone are not sufficient. Many smallholder farmers in developing countries lack access to the inputs, credit, and knowledge needed to adopt new technologies. Furthermore, the environmental impacts of intensive agriculture, including soil degradation, water pollution, and greenhouse gas emissions, must be considered.",
      "Reducing food waste is another critical strategy for improving food security. Approximately one-third of all food produced for human consumption is lost or wasted each year. In developed countries, much of this waste occurs at the retail and consumer levels, while in developing countries, losses often occur during storage and transportation due to inadequate infrastructure.",
      "Dietary changes also have an important role to play. The global demand for meat and dairy products is rising as populations become wealthier. Livestock production requires significantly more land and water than plant-based foods, and generates substantial greenhouse gas emissions. Shifting towards more plant-based diets could free up resources for direct human consumption.",
      "Climate change poses additional challenges for food production. Rising temperatures, changing precipitation patterns, and more frequent extreme weather events are already affecting crop yields in many regions. Developing climate-resilient crop varieties and adapting agricultural practices to changing conditions will be essential for ensuring food security in the future.",
      "Food systems are also interconnected with energy systems. Biofuel production, for example, competes with food production for land and water resources. The energy intensity of modern food systems, from fertiliser production to transportation and refrigeration, contributes significantly to greenhouse gas emissions.",
      "Addressing global food security will require a combination of approaches, including technological innovation, policy changes, and shifts in consumer behaviour. There is no single solution, but rather a need for integrated strategies that consider the environmental, social, and economic dimensions of food production and consumption."
    ]
  },
  'r-p3-antarctica': {
    title: "Antarctic Exploration",
    subtitle: "The development of exploration and scientific research in Antarctica",
    content: [
      "Antarctica has long captivated the imagination of explorers and scientists alike. The frozen continent, covering nearly 14 million square kilometres, represents one of Earth's last frontiers. Its extreme environment, with temperatures that can drop to -80 degrees Celsius and winds that exceed 200 kilometres per hour, has presented enormous challenges for those who have sought to explore and understand it.",
      "The early history of Antarctic exploration was marked by fierce competition between nations seeking to claim territory and achieve geographic firsts. The Heroic Age of Antarctic Exploration, from roughly 1895 to 1922, saw expeditions from Britain, Norway, Sweden, Germany, and other countries venture into the Antarctic wilderness. Many of these expeditions ended in tragedy, with explorers dying from starvation, cold, or accident.",
      "The race to reach the South Pole was a defining moment in Antarctic history. In December 1911, Roald Amundsen's Norwegian expedition became the first to reach the pole, beating Robert Falcon Scott's British team by just over a month. Scott and four companions died on the return journey, highlighting the terrible risks of polar exploration.",
      "The mid-20th century brought a new era of scientific investigation. The International Geophysical Year of 1957-1958 sparked a surge in Antarctic research, with dozens of countries establishing permanent research stations on the continent. The Antarctic Treaty of 1959, signed by 12 nations, set aside Antarctica for peaceful purposes and promoted scientific cooperation.",
      "Today, Antarctica is home to over 70 research stations operated by more than 30 countries. Scientists from around the world travel to the continent to study everything from climate change to astronomy to the unique wildlife that inhabits its coastal waters. The ice sheets of Antarctica contain a record of Earth's climate history stretching back millions of years, making the continent invaluable for understanding our planet's past and future.",
      "Climate research has become an increasingly important focus of Antarctic science. The West Antarctic Ice Sheet, which contains enough water to raise global sea levels by several metres, is showing signs of instability. Scientists are closely monitoring these changes to understand how they might affect coastlines around the world.",
      "The challenges of working in Antarctica are substantial. The extreme cold, isolation, and logistical difficulties make research expensive and dangerous. Supplies must be shipped or flown in during the brief summer months, and researchers must undergo extensive training to cope with the harsh conditions.",
      "Despite these challenges, Antarctica continues to attract scientists and adventurers from around the world. The continent's unique environment offers opportunities for research that cannot be conducted anywhere else on Earth. As we face global challenges like climate change, the importance of understanding this remote and fragile region has never been greater."
    ]
  }
};
